# in this pipeline we are calling init from using templates and its associated variables and hardcoded variables
parameters:
  - name: environment
    displayName: Enter Your Environment name 
    type: string
    default: dev
    values:
      - dev
      - stage
      - prod


trigger: 
 branches:
  include:
    - dev
resources:
 repositories:
   - repository: templates
     name: tripathicle/templates
     type: github
     endpoint: pat-github-svc-pipeline
     ref: refs/heads/main

# declaring variables for resuability

variables:
  workingDir: '$(System.DefaultWorkingDirectory)/Environment/${{parameters.environment}}'
  serviceConnection: 'rakshak-svc'
  storageAccount: 'rakshakstg1'
  containerName: 'tfstate'
  #tfstateKey: 'dev.terraform.tfstate'
  tfstateKey: '${{ parameters.environment }}.terraform.tfstate'

stages:
  - stage: INIT
    displayName: Terraform init
    pool: Rakshak Pipelines
    jobs:
      - template: templates/jobinit.yml@templates
        parameters:
          workingDir: '$(System.DefaultWorkingDirectory)/Environment/${{parameters.environment}}'
          serviceConnection: $(serviceConnection)
          storageAccount: $(storageAccount)
          containerName: $(containerName)
          tfstateKey: '${{ parameters.environment }}.terraform.tfstate'
        
  - stage: VALIDATE
    displayName: terraform validate
    pool: Rakshak Pipelines
    jobs:
      - job: terraformvalidate
        displayName: terraform validate
        #dependsOn: INIT
        steps:

          # - task: TerraformTask@5
          #   inputs:
          #     provider: 'azurerm'
          #     command: 'init'
          #     workingDirectory: '$(System.DefaultWorkingDirectory)\Environment\Dev'
          #     backendServiceArm: 'rakshak-svc'
          #     backendAzureRmStorageAccountName: 'rakshakstg1'
          #     backendAzureRmContainerName: 'tfstate'
          #     backendAzureRmKey: 'dev.terraform.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{parameters.environment}}'
              backendServiceArm: $(serviceConnection)
              backendAzureRmStorageAccountName: $(storageAccount)
              backendAzureRmContainerName: $(containerName)
              backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '${{ parameters.environment }}.terraform.tfstate'


  - stage: PLAN
    displayName: terraform Plan
    pool: Rakshak Pipelines
    dependsOn: VALIDATE
    jobs:
      - job: terraformvalidate
        displayName: terraform Plan
        steps:
         - task: TerraformTask@5
           inputs:
             provider: 'azurerm'
             command: 'plan'
             workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{parameters.environment}}'
             environmentServiceNameAzureRM: 'rakshak-svc'


  - stage: Apply
    displayName: terraform Apply
    pool: Rakshak Pipelines
    dependsOn: PLAN
    jobs:
      - job: terraformApply
        displayName: terraform Apply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{parameters.environment}}'
              environmentServiceNameAzureRM: 'rakshak-svc'
        


  

         

      
        


   

