trigger:
- dev
jobs:

  - job: 
    displayName: verifying terraform init
    pool: AagentRakshakPoolYml
    steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)\Environment\Dev'
          backendServiceArm: 'rakshak-app-manual-svc'
          backendAzureRmStorageAccountName: 'rakshakstg1'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'dev.terraform.tfstate'