trigger:
 branches:
   include:
     
     - dev

stages:
  - stage: terraforminit
    displayName: terraform stage init
    pool: Rakshak Pipelines
    jobs:
    - template: templates/terraform-init-jobs.yml
      

  - stage: terraformvalidate
    displayName: terraform stage validate
    dependsOn: terraforminit
    pool: Rakshak Pipelines
    jobs:
      - job: terraformvalidate
        displayName: terraformstagevalidate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Environment\Dev'
              backendServiceArm: 'rakshak-svc'
              backendAzureRmStorageAccountName: 'rakshakstg1'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'

  - stage: terraformPlan
    displayName: terraform stage Plan
    dependsOn: terraformvalidate
    pool: Rakshak Pipelines
    jobs:
      - job: terraformPlan
        displayName: terraform stage plan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Environment\Dev'
              backendServiceArm: 'rakshak-svc'
              backendAzureRmStorageAccountName: 'rakshakstg1'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'            
          
          
  - stage: terraformApply
    displayName: terraform stage apply
    dependsOn: terraformPlan
    pool: Rakshak Pipelines
    jobs:
      - job: terraformPlan
        displayName: terraform stage Apply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Environment\Dev'
              backendServiceArm: 'rakshak-svc'
              backendAzureRmStorageAccountName: 'rakshakstg1'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'            
          


    