trigger:
 branches:
   include:
     
     - dev

stages:
  - stage: terraforminit
    displayName: terraform init
    pool: Rakshak Pipelines
    jobs:
      - job: 
        displayName: terraforminit
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Environment\Dev'
              backendServiceArm: 'rakshak-svc'
              backendAzureRmStorageAccountName: 'rakshakstg1'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'

  - stage: terraformvalidate
    displayName: terraform validate
    dependsOn:  terraforminit
    pool: Rakshak Pipelines
    jobs:
      - job: 
        displayName: terraformvalidate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Environment\Dev'
              backendServiceArm: 'rakshak-svc'
              backendAzureRmStorageAccountName: 'rakshakstg1'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'

  - stage: terraformvalidate
    displayName: terraform plan
    dependsOn:  terraformvalidate
    pool: Rakshak Pipelines
    jobs:
      - job: 
        displayName: terraformvalidate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\Environment\Dev'
              backendServiceArm: 'rakshak-svc'
              backendAzureRmStorageAccountName: 'rakshakstg1'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'




         
    
    
    
  
          


